services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: ["argmining-app"]
  grpc:
    build: .
    ports:
      - "50051:50051"
    command: ["argmining-grpc"]
  eval:
    build: .
    command: ["argmining-eval"]
