# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/cbr/v1beta/casebase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arg_services.cbr.v1beta import model_pb2 as arg__services_dot_cbr_dot_v1beta_dot_model__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/cbr/v1beta/casebase.proto',
  package='arg_services.cbr.v1beta',
  syntax='proto3',
  serialized_options=b'\n\033com.arg_services.cbr.v1betaB\rCasebaseProtoP\001\242\002\003ACX\252\002\026ArgServices.Cbr.V1beta\312\002\026ArgServices\\Cbr\\V1beta\342\002\"ArgServices\\Cbr\\V1beta\\GPBMetadata\352\002\030ArgServices::Cbr::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&arg_services/cbr/v1beta/casebase.proto\x12\x17\x61rg_services.cbr.v1beta\x1a#arg_services/cbr/v1beta/model.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc8\x01\n\x0f\x43\x61sebaseRequest\x12\x41\n\x07include\x18\x01 \x01(\x0b\x32\'.arg_services.cbr.v1beta.CasebaseFilterR\x07include\x12\x41\n\x07\x65xclude\x18\x02 \x01(\x0b\x32\'.arg_services.cbr.v1beta.CasebaseFilterR\x07\x65xclude\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\xc1\x01\n\x10\x43\x61sebaseResponse\x12J\n\x05\x63\x61ses\x18\x01 \x03(\x0b\x32\x34.arg_services.cbr.v1beta.CasebaseResponse.CasesEntryR\x05\x63\x61ses\x1a\x61\n\nCasesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12=\n\x05value\x18\x02 \x01(\x0b\x32\'.arg_services.cbr.v1beta.AnnotatedGraphR\x05value:\x02\x38\x01\x32\x94\x01\n\x0f\x43\x61sebaseService\x12\x80\x01\n\x08\x43\x61sebase\x12(.arg_services.cbr.v1beta.CasebaseRequest\x1a).arg_services.cbr.v1beta.CasebaseResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/cbr/v1beta/casebaseB\xa6\x01\n\x1b\x63om.arg_services.cbr.v1betaB\rCasebaseProtoP\x01\xa2\x02\x03\x41\x43X\xaa\x02\x16\x41rgServices.Cbr.V1beta\xca\x02\x16\x41rgServices\\Cbr\\V1beta\xe2\x02\"ArgServices\\Cbr\\V1beta\\GPBMetadata\xea\x02\x18\x41rgServices::Cbr::V1betab\x06proto3'
  ,
  dependencies=[arg__services_dot_cbr_dot_v1beta_dot_model__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CASEBASEREQUEST = _descriptor.Descriptor(
  name='CasebaseRequest',
  full_name='arg_services.cbr.v1beta.CasebaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='include', full_name='arg_services.cbr.v1beta.CasebaseRequest.include', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='include', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclude', full_name='arg_services.cbr.v1beta.CasebaseRequest.exclude', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='exclude', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.cbr.v1beta.CasebaseRequest.extras', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=365,
)


_CASEBASERESPONSE_CASESENTRY = _descriptor.Descriptor(
  name='CasesEntry',
  full_name='arg_services.cbr.v1beta.CasebaseResponse.CasesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arg_services.cbr.v1beta.CasebaseResponse.CasesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arg_services.cbr.v1beta.CasebaseResponse.CasesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=561,
)

_CASEBASERESPONSE = _descriptor.Descriptor(
  name='CasebaseResponse',
  full_name='arg_services.cbr.v1beta.CasebaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cases', full_name='arg_services.cbr.v1beta.CasebaseResponse.cases', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='cases', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CASEBASERESPONSE_CASESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=561,
)

_CASEBASEREQUEST.fields_by_name['include'].message_type = arg__services_dot_cbr_dot_v1beta_dot_model__pb2._CASEBASEFILTER
_CASEBASEREQUEST.fields_by_name['exclude'].message_type = arg__services_dot_cbr_dot_v1beta_dot_model__pb2._CASEBASEFILTER
_CASEBASEREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_CASEBASERESPONSE_CASESENTRY.fields_by_name['value'].message_type = arg__services_dot_cbr_dot_v1beta_dot_model__pb2._ANNOTATEDGRAPH
_CASEBASERESPONSE_CASESENTRY.containing_type = _CASEBASERESPONSE
_CASEBASERESPONSE.fields_by_name['cases'].message_type = _CASEBASERESPONSE_CASESENTRY
DESCRIPTOR.message_types_by_name['CasebaseRequest'] = _CASEBASEREQUEST
DESCRIPTOR.message_types_by_name['CasebaseResponse'] = _CASEBASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CasebaseRequest = _reflection.GeneratedProtocolMessageType('CasebaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CASEBASEREQUEST,
  '__module__' : 'arg_services.cbr.v1beta.casebase_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.CasebaseRequest)
  })
_sym_db.RegisterMessage(CasebaseRequest)

CasebaseResponse = _reflection.GeneratedProtocolMessageType('CasebaseResponse', (_message.Message,), {

  'CasesEntry' : _reflection.GeneratedProtocolMessageType('CasesEntry', (_message.Message,), {
    'DESCRIPTOR' : _CASEBASERESPONSE_CASESENTRY,
    '__module__' : 'arg_services.cbr.v1beta.casebase_pb2'
    # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.CasebaseResponse.CasesEntry)
    })
  ,
  'DESCRIPTOR' : _CASEBASERESPONSE,
  '__module__' : 'arg_services.cbr.v1beta.casebase_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.CasebaseResponse)
  })
_sym_db.RegisterMessage(CasebaseResponse)
_sym_db.RegisterMessage(CasebaseResponse.CasesEntry)


DESCRIPTOR._options = None
_CASEBASERESPONSE_CASESENTRY._options = None

_CASEBASESERVICE = _descriptor.ServiceDescriptor(
  name='CasebaseService',
  full_name='arg_services.cbr.v1beta.CasebaseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=564,
  serialized_end=712,
  methods=[
  _descriptor.MethodDescriptor(
    name='Casebase',
    full_name='arg_services.cbr.v1beta.CasebaseService.Casebase',
    index=0,
    containing_service=None,
    input_type=_CASEBASEREQUEST,
    output_type=_CASEBASERESPONSE,
    serialized_options=b'\202\323\344\223\002\031:\001*\"\024/cbr/v1beta/casebase',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASEBASESERVICE)

DESCRIPTOR.services_by_name['CasebaseService'] = _CASEBASESERVICE

# @@protoc_insertion_point(module_scope)
