# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/cbr/v1beta/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arg_services.graph.v1 import graph_pb2 as arg__services_dot_graph_dot_v1_dot_graph__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/cbr/v1beta/model.proto',
  package='arg_services.cbr.v1beta',
  syntax='proto3',
  serialized_options=b'\n\033com.arg_services.cbr.v1betaB\nModelProtoP\001\242\002\003ACX\252\002\026ArgServices.Cbr.V1beta\312\002\026ArgServices\\Cbr\\V1beta\342\002\"ArgServices\\Cbr\\V1beta\\GPBMetadata\352\002\030ArgServices::Cbr::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#arg_services/cbr/v1beta/model.proto\x12\x17\x61rg_services.cbr.v1beta\x1a!arg_services/graph/v1/graph.proto\"X\n\x0e\x41nnotatedGraph\x12\x32\n\x05graph\x18\x01 \x01(\x0b\x32\x1c.arg_services.graph.v1.GraphR\x05graph\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text\"\xc2\x01\n\x0e\x43\x61sebaseFilter\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05\x63\x61ses\x18\x02 \x01(\tR\x05\x63\x61ses\x12K\n\x06kwargs\x18\x03 \x03(\x0b\x32\x33.arg_services.cbr.v1beta.CasebaseFilter.KwargsEntryR\x06kwargs\x1a\x39\n\x0bKwargsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xa3\x01\n\x1b\x63om.arg_services.cbr.v1betaB\nModelProtoP\x01\xa2\x02\x03\x41\x43X\xaa\x02\x16\x41rgServices.Cbr.V1beta\xca\x02\x16\x41rgServices\\Cbr\\V1beta\xe2\x02\"ArgServices\\Cbr\\V1beta\\GPBMetadata\xea\x02\x18\x41rgServices::Cbr::V1betab\x06proto3'
  ,
  dependencies=[arg__services_dot_graph_dot_v1_dot_graph__pb2.DESCRIPTOR,])




_ANNOTATEDGRAPH = _descriptor.Descriptor(
  name='AnnotatedGraph',
  full_name='arg_services.cbr.v1beta.AnnotatedGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph', full_name='arg_services.cbr.v1beta.AnnotatedGraph.graph', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='graph', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='arg_services.cbr.v1beta.AnnotatedGraph.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='text', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=187,
)


_CASEBASEFILTER_KWARGSENTRY = _descriptor.Descriptor(
  name='KwargsEntry',
  full_name='arg_services.cbr.v1beta.CasebaseFilter.KwargsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arg_services.cbr.v1beta.CasebaseFilter.KwargsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arg_services.cbr.v1beta.CasebaseFilter.KwargsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=384,
)

_CASEBASEFILTER = _descriptor.Descriptor(
  name='CasebaseFilter',
  full_name='arg_services.cbr.v1beta.CasebaseFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='arg_services.cbr.v1beta.CasebaseFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cases', full_name='arg_services.cbr.v1beta.CasebaseFilter.cases', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='cases', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='arg_services.cbr.v1beta.CasebaseFilter.kwargs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='kwargs', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CASEBASEFILTER_KWARGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=384,
)

_ANNOTATEDGRAPH.fields_by_name['graph'].message_type = arg__services_dot_graph_dot_v1_dot_graph__pb2._GRAPH
_CASEBASEFILTER_KWARGSENTRY.containing_type = _CASEBASEFILTER
_CASEBASEFILTER.fields_by_name['kwargs'].message_type = _CASEBASEFILTER_KWARGSENTRY
DESCRIPTOR.message_types_by_name['AnnotatedGraph'] = _ANNOTATEDGRAPH
DESCRIPTOR.message_types_by_name['CasebaseFilter'] = _CASEBASEFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotatedGraph = _reflection.GeneratedProtocolMessageType('AnnotatedGraph', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATEDGRAPH,
  '__module__' : 'arg_services.cbr.v1beta.model_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.AnnotatedGraph)
  })
_sym_db.RegisterMessage(AnnotatedGraph)

CasebaseFilter = _reflection.GeneratedProtocolMessageType('CasebaseFilter', (_message.Message,), {

  'KwargsEntry' : _reflection.GeneratedProtocolMessageType('KwargsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CASEBASEFILTER_KWARGSENTRY,
    '__module__' : 'arg_services.cbr.v1beta.model_pb2'
    # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.CasebaseFilter.KwargsEntry)
    })
  ,
  'DESCRIPTOR' : _CASEBASEFILTER,
  '__module__' : 'arg_services.cbr.v1beta.model_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.cbr.v1beta.CasebaseFilter)
  })
_sym_db.RegisterMessage(CasebaseFilter)
_sym_db.RegisterMessage(CasebaseFilter.KwargsEntry)


DESCRIPTOR._options = None
_CASEBASEFILTER_KWARGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
