# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.cbr.v1beta import retrieval_pb2 as arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2


class RetrievalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/arg_services.cbr.v1beta.RetrievalService/Retrieve',
                request_serializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveResponse.FromString,
                )
        self.Similarities = channel.unary_unary(
                '/arg_services.cbr.v1beta.RetrievalService/Similarities',
                request_serializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesRequest.SerializeToString,
                response_deserializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesResponse.FromString,
                )


class RetrievalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Similarities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveRequest.FromString,
                    response_serializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveResponse.SerializeToString,
            ),
            'Similarities': grpc.unary_unary_rpc_method_handler(
                    servicer.Similarities,
                    request_deserializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesRequest.FromString,
                    response_serializer=arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.cbr.v1beta.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.cbr.v1beta.RetrievalService/Retrieve',
            arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
            arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.RetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Similarities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.cbr.v1beta.RetrievalService/Similarities',
            arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesRequest.SerializeToString,
            arg__services_dot_cbr_dot_v1beta_dot_retrieval__pb2.SimilaritiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
