# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.mining.v1beta import graph_construction_pb2 as arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2


class GraphConstructionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GraphConstruction = channel.unary_unary(
                '/arg_services.mining.v1beta.GraphConstructionService/GraphConstruction',
                request_serializer=arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionRequest.SerializeToString,
                response_deserializer=arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionResponse.FromString,
                )


class GraphConstructionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GraphConstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphConstructionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GraphConstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphConstruction,
                    request_deserializer=arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionRequest.FromString,
                    response_serializer=arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.mining.v1beta.GraphConstructionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphConstructionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GraphConstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.mining.v1beta.GraphConstructionService/GraphConstruction',
            arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionRequest.SerializeToString,
            arg__services_dot_mining_dot_v1beta_dot_graph__construction__pb2.GraphConstructionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
