# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining/v1beta/graph_construction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arg_services.graph.v1 import graph_pb2 as arg__services_dot_graph_dot_v1_dot_graph__pb2
from arg_services.mining.v1beta import adu_pb2 as arg__services_dot_mining_dot_v1beta_dot_adu__pb2
from arg_services.mining.v1beta import entailment_pb2 as arg__services_dot_mining_dot_v1beta_dot_entailment__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/mining/v1beta/graph_construction.proto',
  package='arg_services.mining.v1beta',
  syntax='proto3',
  serialized_options=b'\n\036com.arg_services.mining.v1betaB\026GraphConstructionProtoP\001\242\002\003AMX\252\002\031ArgServices.Mining.V1beta\312\002\031ArgServices\\Mining\\V1beta\342\002%ArgServices\\Mining\\V1beta\\GPBMetadata\352\002\033ArgServices::Mining::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3arg_services/mining/v1beta/graph_construction.proto\x12\x1a\x61rg_services.mining.v1beta\x1a!arg_services/graph/v1/graph.proto\x1a$arg_services/mining/v1beta/adu.proto\x1a+arg_services/mining/v1beta/entailment.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x89\x03\n\x18GraphConstructionRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language\x12R\n\x04\x61\x64us\x18\x02 \x03(\x0b\x32>.arg_services.mining.v1beta.GraphConstructionRequest.AdusEntryR\x04\x61\x64us\x12$\n\x0emajor_claim_id\x18\x03 \x01(\tR\x0cmajorClaimId\x12H\n\x0b\x65ntailments\x18\x04 \x03(\x0b\x32&.arg_services.mining.v1beta.EntailmentR\x0b\x65ntailments\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\x1a\\\n\tAdusEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32#.arg_services.mining.v1beta.SegmentR\x05value:\x02\x38\x01\"\x80\x01\n\x19GraphConstructionResponse\x12\x32\n\x05graph\x18\x01 \x01(\x0b\x32\x1c.arg_services.graph.v1.GraphR\x05graph\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras2\xcb\x01\n\x18GraphConstructionService\x12\xae\x01\n\x11GraphConstruction\x12\x34.arg_services.mining.v1beta.GraphConstructionRequest\x1a\x35.arg_services.mining.v1beta.GraphConstructionResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/mining/v1beta/graph_constructionB\xbe\x01\n\x1e\x63om.arg_services.mining.v1betaB\x16GraphConstructionProtoP\x01\xa2\x02\x03\x41MX\xaa\x02\x19\x41rgServices.Mining.V1beta\xca\x02\x19\x41rgServices\\Mining\\V1beta\xe2\x02%ArgServices\\Mining\\V1beta\\GPBMetadata\xea\x02\x1b\x41rgServices::Mining::V1betab\x06proto3'
  ,
  dependencies=[arg__services_dot_graph_dot_v1_dot_graph__pb2.DESCRIPTOR,arg__services_dot_mining_dot_v1beta_dot_adu__pb2.DESCRIPTOR,arg__services_dot_mining_dot_v1beta_dot_entailment__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_GRAPHCONSTRUCTIONREQUEST_ADUSENTRY = _descriptor.Descriptor(
  name='AdusEntry',
  full_name='arg_services.mining.v1beta.GraphConstructionRequest.AdusEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arg_services.mining.v1beta.GraphConstructionRequest.AdusEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arg_services.mining.v1beta.GraphConstructionRequest.AdusEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=655,
)

_GRAPHCONSTRUCTIONREQUEST = _descriptor.Descriptor(
  name='GraphConstructionRequest',
  full_name='arg_services.mining.v1beta.GraphConstructionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='arg_services.mining.v1beta.GraphConstructionRequest.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='language', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adus', full_name='arg_services.mining.v1beta.GraphConstructionRequest.adus', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='adus', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='major_claim_id', full_name='arg_services.mining.v1beta.GraphConstructionRequest.major_claim_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='majorClaimId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entailments', full_name='arg_services.mining.v1beta.GraphConstructionRequest.entailments', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='entailments', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining.v1beta.GraphConstructionRequest.extras', index=4,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GRAPHCONSTRUCTIONREQUEST_ADUSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=655,
)


_GRAPHCONSTRUCTIONRESPONSE = _descriptor.Descriptor(
  name='GraphConstructionResponse',
  full_name='arg_services.mining.v1beta.GraphConstructionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph', full_name='arg_services.mining.v1beta.GraphConstructionResponse.graph', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='graph', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining.v1beta.GraphConstructionResponse.extras', index=1,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=786,
)

_GRAPHCONSTRUCTIONREQUEST_ADUSENTRY.fields_by_name['value'].message_type = arg__services_dot_mining_dot_v1beta_dot_adu__pb2._SEGMENT
_GRAPHCONSTRUCTIONREQUEST_ADUSENTRY.containing_type = _GRAPHCONSTRUCTIONREQUEST
_GRAPHCONSTRUCTIONREQUEST.fields_by_name['adus'].message_type = _GRAPHCONSTRUCTIONREQUEST_ADUSENTRY
_GRAPHCONSTRUCTIONREQUEST.fields_by_name['entailments'].message_type = arg__services_dot_mining_dot_v1beta_dot_entailment__pb2._ENTAILMENT
_GRAPHCONSTRUCTIONREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GRAPHCONSTRUCTIONRESPONSE.fields_by_name['graph'].message_type = arg__services_dot_graph_dot_v1_dot_graph__pb2._GRAPH
_GRAPHCONSTRUCTIONRESPONSE.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['GraphConstructionRequest'] = _GRAPHCONSTRUCTIONREQUEST
DESCRIPTOR.message_types_by_name['GraphConstructionResponse'] = _GRAPHCONSTRUCTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphConstructionRequest = _reflection.GeneratedProtocolMessageType('GraphConstructionRequest', (_message.Message,), {

  'AdusEntry' : _reflection.GeneratedProtocolMessageType('AdusEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPHCONSTRUCTIONREQUEST_ADUSENTRY,
    '__module__' : 'arg_services.mining.v1beta.graph_construction_pb2'
    # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.GraphConstructionRequest.AdusEntry)
    })
  ,
  'DESCRIPTOR' : _GRAPHCONSTRUCTIONREQUEST,
  '__module__' : 'arg_services.mining.v1beta.graph_construction_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.GraphConstructionRequest)
  })
_sym_db.RegisterMessage(GraphConstructionRequest)
_sym_db.RegisterMessage(GraphConstructionRequest.AdusEntry)

GraphConstructionResponse = _reflection.GeneratedProtocolMessageType('GraphConstructionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHCONSTRUCTIONRESPONSE,
  '__module__' : 'arg_services.mining.v1beta.graph_construction_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.GraphConstructionResponse)
  })
_sym_db.RegisterMessage(GraphConstructionResponse)


DESCRIPTOR._options = None
_GRAPHCONSTRUCTIONREQUEST_ADUSENTRY._options = None

_GRAPHCONSTRUCTIONSERVICE = _descriptor.ServiceDescriptor(
  name='GraphConstructionService',
  full_name='arg_services.mining.v1beta.GraphConstructionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=789,
  serialized_end=992,
  methods=[
  _descriptor.MethodDescriptor(
    name='GraphConstruction',
    full_name='arg_services.mining.v1beta.GraphConstructionService.GraphConstruction',
    index=0,
    containing_service=None,
    input_type=_GRAPHCONSTRUCTIONREQUEST,
    output_type=_GRAPHCONSTRUCTIONRESPONSE,
    serialized_options=b'\202\323\344\223\002&:\001*\"!/mining/v1beta/graph_construction',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRAPHCONSTRUCTIONSERVICE)

DESCRIPTOR.services_by_name['GraphConstructionService'] = _GRAPHCONSTRUCTIONSERVICE

# @@protoc_insertion_point(module_scope)
