# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining/v1beta/major_claim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arg_services.mining.v1beta import adu_pb2 as arg__services_dot_mining_dot_v1beta_dot_adu__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/mining/v1beta/major_claim.proto',
  package='arg_services.mining.v1beta',
  syntax='proto3',
  serialized_options=b'\n\036com.arg_services.mining.v1betaB\017MajorClaimProtoP\001\242\002\003AMX\252\002\031ArgServices.Mining.V1beta\312\002\031ArgServices\\Mining\\V1beta\342\002%ArgServices\\Mining\\V1beta\\GPBMetadata\352\002\033ArgServices::Mining::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,arg_services/mining/v1beta/major_claim.proto\x12\x1a\x61rg_services.mining.v1beta\x1a$arg_services/mining/v1beta/adu.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb1\x02\n\x11MajorClaimRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language\x12W\n\x08segments\x18\x02 \x03(\x0b\x32;.arg_services.mining.v1beta.MajorClaimRequest.SegmentsEntryR\x08segments\x12\x14\n\x05limit\x18\x04 \x01(\x04R\x05limit\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\x1a`\n\rSegmentsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32#.arg_services.mining.v1beta.SegmentR\x05value:\x02\x38\x01\"\x8d\x01\n\x12MajorClaimResponse\x12\x46\n\x07ranking\x18\x01 \x03(\x0b\x32,.arg_services.mining.v1beta.MajorClaimResultR\x07ranking\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"D\n\x10MajorClaimResult\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12 \n\x0bprobability\x18\x02 \x01(\x01R\x0bprobability2\xa8\x01\n\x11MajorClaimService\x12\x92\x01\n\nMajorClaim\x12-.arg_services.mining.v1beta.MajorClaimRequest\x1a..arg_services.mining.v1beta.MajorClaimResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/mining/v1beta/major_claimB\xb7\x01\n\x1e\x63om.arg_services.mining.v1betaB\x0fMajorClaimProtoP\x01\xa2\x02\x03\x41MX\xaa\x02\x19\x41rgServices.Mining.V1beta\xca\x02\x19\x41rgServices\\Mining\\V1beta\xe2\x02%ArgServices\\Mining\\V1beta\\GPBMetadata\xea\x02\x1b\x41rgServices::Mining::V1betab\x06proto3'
  ,
  dependencies=[arg__services_dot_mining_dot_v1beta_dot_adu__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_MAJORCLAIMREQUEST_SEGMENTSENTRY = _descriptor.Descriptor(
  name='SegmentsEntry',
  full_name='arg_services.mining.v1beta.MajorClaimRequest.SegmentsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arg_services.mining.v1beta.MajorClaimRequest.SegmentsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arg_services.mining.v1beta.MajorClaimRequest.SegmentsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=480,
)

_MAJORCLAIMREQUEST = _descriptor.Descriptor(
  name='MajorClaimRequest',
  full_name='arg_services.mining.v1beta.MajorClaimRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='arg_services.mining.v1beta.MajorClaimRequest.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='language', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segments', full_name='arg_services.mining.v1beta.MajorClaimRequest.segments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='segments', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='arg_services.mining.v1beta.MajorClaimRequest.limit', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='limit', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining.v1beta.MajorClaimRequest.extras', index=3,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAJORCLAIMREQUEST_SEGMENTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=480,
)


_MAJORCLAIMRESPONSE = _descriptor.Descriptor(
  name='MajorClaimResponse',
  full_name='arg_services.mining.v1beta.MajorClaimResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranking', full_name='arg_services.mining.v1beta.MajorClaimResponse.ranking', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='ranking', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining.v1beta.MajorClaimResponse.extras', index=1,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=624,
)


_MAJORCLAIMRESULT = _descriptor.Descriptor(
  name='MajorClaimResult',
  full_name='arg_services.mining.v1beta.MajorClaimResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='arg_services.mining.v1beta.MajorClaimResult.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability', full_name='arg_services.mining.v1beta.MajorClaimResult.probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='probability', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=694,
)

_MAJORCLAIMREQUEST_SEGMENTSENTRY.fields_by_name['value'].message_type = arg__services_dot_mining_dot_v1beta_dot_adu__pb2._SEGMENT
_MAJORCLAIMREQUEST_SEGMENTSENTRY.containing_type = _MAJORCLAIMREQUEST
_MAJORCLAIMREQUEST.fields_by_name['segments'].message_type = _MAJORCLAIMREQUEST_SEGMENTSENTRY
_MAJORCLAIMREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_MAJORCLAIMRESPONSE.fields_by_name['ranking'].message_type = _MAJORCLAIMRESULT
_MAJORCLAIMRESPONSE.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['MajorClaimRequest'] = _MAJORCLAIMREQUEST
DESCRIPTOR.message_types_by_name['MajorClaimResponse'] = _MAJORCLAIMRESPONSE
DESCRIPTOR.message_types_by_name['MajorClaimResult'] = _MAJORCLAIMRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MajorClaimRequest = _reflection.GeneratedProtocolMessageType('MajorClaimRequest', (_message.Message,), {

  'SegmentsEntry' : _reflection.GeneratedProtocolMessageType('SegmentsEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAJORCLAIMREQUEST_SEGMENTSENTRY,
    '__module__' : 'arg_services.mining.v1beta.major_claim_pb2'
    # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.MajorClaimRequest.SegmentsEntry)
    })
  ,
  'DESCRIPTOR' : _MAJORCLAIMREQUEST,
  '__module__' : 'arg_services.mining.v1beta.major_claim_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.MajorClaimRequest)
  })
_sym_db.RegisterMessage(MajorClaimRequest)
_sym_db.RegisterMessage(MajorClaimRequest.SegmentsEntry)

MajorClaimResponse = _reflection.GeneratedProtocolMessageType('MajorClaimResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAJORCLAIMRESPONSE,
  '__module__' : 'arg_services.mining.v1beta.major_claim_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.MajorClaimResponse)
  })
_sym_db.RegisterMessage(MajorClaimResponse)

MajorClaimResult = _reflection.GeneratedProtocolMessageType('MajorClaimResult', (_message.Message,), {
  'DESCRIPTOR' : _MAJORCLAIMRESULT,
  '__module__' : 'arg_services.mining.v1beta.major_claim_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining.v1beta.MajorClaimResult)
  })
_sym_db.RegisterMessage(MajorClaimResult)


DESCRIPTOR._options = None
_MAJORCLAIMREQUEST_SEGMENTSENTRY._options = None

_MAJORCLAIMSERVICE = _descriptor.ServiceDescriptor(
  name='MajorClaimService',
  full_name='arg_services.mining.v1beta.MajorClaimService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=697,
  serialized_end=865,
  methods=[
  _descriptor.MethodDescriptor(
    name='MajorClaim',
    full_name='arg_services.mining.v1beta.MajorClaimService.MajorClaim',
    index=0,
    containing_service=None,
    input_type=_MAJORCLAIMREQUEST,
    output_type=_MAJORCLAIMRESPONSE,
    serialized_options=b'\202\323\344\223\002\037:\001*\"\032/mining/v1beta/major_claim',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAJORCLAIMSERVICE)

DESCRIPTOR.services_by_name['MajorClaimService'] = _MAJORCLAIMSERVICE

# @@protoc_insertion_point(module_scope)
