# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/quality/v1beta/expert.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/quality/v1beta/expert.proto',
  package='arg_services.quality.v1beta',
  syntax='proto3',
  serialized_options=b'\n\037com.arg_services.quality.v1betaB\013ExpertProtoP\001\242\002\003AQX\252\002\032ArgServices.Quality.V1beta\312\002\032ArgServices\\Quality\\V1beta\342\002&ArgServices\\Quality\\V1beta\\GPBMetadata\352\002\034ArgServices::Quality::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(arg_services/quality/v1beta/expert.proto\x12\x1b\x61rg_services.quality.v1beta\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9c\x02\n\x15\x45xpertSuitableRequest\x12\x18\n\x07premise\x18\x01 \x01(\tR\x07premise\x12\x1d\n\nscholar_id\x18\x02 \x01(\tR\tscholarId\x12\\\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32@.arg_services.quality.v1beta.ExpertSuitableRequest.FeaturesEntryR\x08\x66\x65\x61tures\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\x1a;\n\rFeaturesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xe1\x01\n\x16\x45xpertSuitableResponse\x12@\n\x04type\x18\x01 \x01(\x0e\x32,.arg_services.quality.v1beta.SuitabilityTypeR\x04type\x12T\n\x0bpredictions\x18\x02 \x03(\x0b\x32\x32.arg_services.quality.v1beta.SuitabilityPredictionR\x0bpredictions\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"{\n\x15SuitabilityPrediction\x12 \n\x0bprobability\x18\x01 \x01(\x01R\x0bprobability\x12@\n\x04type\x18\x02 \x01(\x0e\x32,.arg_services.quality.v1beta.SuitabilityTypeR\x04type*\x9f\x01\n\x0fSuitabilityType\x12 \n\x1cSUITABILITY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSUITABILITY_TYPE_NO_EXPERT\x10\x01\x12$\n SUITABILITY_TYPE_SOMEWHAT_EXPERT\x10\x02\x12$\n SUITABILITY_TYPE_ABSOLUTE_EXPERT\x10\x03\x32\xc2\x01\n\x18\x45xpertSuitabilityService\x12\xa5\x01\n\x0e\x45xpertSuitable\x12\x32.arg_services.quality.v1beta.ExpertSuitableRequest\x1a\x33.arg_services.quality.v1beta.ExpertSuitableResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/quality/v1beta/expert_suitableB\xb8\x01\n\x1f\x63om.arg_services.quality.v1betaB\x0b\x45xpertProtoP\x01\xa2\x02\x03\x41QX\xaa\x02\x1a\x41rgServices.Quality.V1beta\xca\x02\x1a\x41rgServices\\Quality\\V1beta\xe2\x02&ArgServices\\Quality\\V1beta\\GPBMetadata\xea\x02\x1c\x41rgServices::Quality::V1betab\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_SUITABILITYTYPE = _descriptor.EnumDescriptor(
  name='SuitabilityType',
  full_name='arg_services.quality.v1beta.SuitabilityType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUITABILITY_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUITABILITY_TYPE_NO_EXPERT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUITABILITY_TYPE_SOMEWHAT_EXPERT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUITABILITY_TYPE_ABSOLUTE_EXPERT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=774,
  serialized_end=933,
)
_sym_db.RegisterEnumDescriptor(_SUITABILITYTYPE)

SuitabilityType = enum_type_wrapper.EnumTypeWrapper(_SUITABILITYTYPE)
SUITABILITY_TYPE_UNSPECIFIED = 0
SUITABILITY_TYPE_NO_EXPERT = 1
SUITABILITY_TYPE_SOMEWHAT_EXPERT = 2
SUITABILITY_TYPE_ABSOLUTE_EXPERT = 3



_EXPERTSUITABLEREQUEST_FEATURESENTRY = _descriptor.Descriptor(
  name='FeaturesEntry',
  full_name='arg_services.quality.v1beta.ExpertSuitableRequest.FeaturesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.FeaturesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.FeaturesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=418,
)

_EXPERTSUITABLEREQUEST = _descriptor.Descriptor(
  name='ExpertSuitableRequest',
  full_name='arg_services.quality.v1beta.ExpertSuitableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='premise', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.premise', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='premise', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scholar_id', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.scholar_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='scholarId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.features', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='features', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.quality.v1beta.ExpertSuitableRequest.extras', index=3,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXPERTSUITABLEREQUEST_FEATURESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=418,
)


_EXPERTSUITABLERESPONSE = _descriptor.Descriptor(
  name='ExpertSuitableResponse',
  full_name='arg_services.quality.v1beta.ExpertSuitableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='arg_services.quality.v1beta.ExpertSuitableResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictions', full_name='arg_services.quality.v1beta.ExpertSuitableResponse.predictions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='predictions', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.quality.v1beta.ExpertSuitableResponse.extras', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=646,
)


_SUITABILITYPREDICTION = _descriptor.Descriptor(
  name='SuitabilityPrediction',
  full_name='arg_services.quality.v1beta.SuitabilityPrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='probability', full_name='arg_services.quality.v1beta.SuitabilityPrediction.probability', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='probability', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='arg_services.quality.v1beta.SuitabilityPrediction.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=771,
)

_EXPERTSUITABLEREQUEST_FEATURESENTRY.containing_type = _EXPERTSUITABLEREQUEST
_EXPERTSUITABLEREQUEST.fields_by_name['features'].message_type = _EXPERTSUITABLEREQUEST_FEATURESENTRY
_EXPERTSUITABLEREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_EXPERTSUITABLERESPONSE.fields_by_name['type'].enum_type = _SUITABILITYTYPE
_EXPERTSUITABLERESPONSE.fields_by_name['predictions'].message_type = _SUITABILITYPREDICTION
_EXPERTSUITABLERESPONSE.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_SUITABILITYPREDICTION.fields_by_name['type'].enum_type = _SUITABILITYTYPE
DESCRIPTOR.message_types_by_name['ExpertSuitableRequest'] = _EXPERTSUITABLEREQUEST
DESCRIPTOR.message_types_by_name['ExpertSuitableResponse'] = _EXPERTSUITABLERESPONSE
DESCRIPTOR.message_types_by_name['SuitabilityPrediction'] = _SUITABILITYPREDICTION
DESCRIPTOR.enum_types_by_name['SuitabilityType'] = _SUITABILITYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpertSuitableRequest = _reflection.GeneratedProtocolMessageType('ExpertSuitableRequest', (_message.Message,), {

  'FeaturesEntry' : _reflection.GeneratedProtocolMessageType('FeaturesEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXPERTSUITABLEREQUEST_FEATURESENTRY,
    '__module__' : 'arg_services.quality.v1beta.expert_pb2'
    # @@protoc_insertion_point(class_scope:arg_services.quality.v1beta.ExpertSuitableRequest.FeaturesEntry)
    })
  ,
  'DESCRIPTOR' : _EXPERTSUITABLEREQUEST,
  '__module__' : 'arg_services.quality.v1beta.expert_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.quality.v1beta.ExpertSuitableRequest)
  })
_sym_db.RegisterMessage(ExpertSuitableRequest)
_sym_db.RegisterMessage(ExpertSuitableRequest.FeaturesEntry)

ExpertSuitableResponse = _reflection.GeneratedProtocolMessageType('ExpertSuitableResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPERTSUITABLERESPONSE,
  '__module__' : 'arg_services.quality.v1beta.expert_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.quality.v1beta.ExpertSuitableResponse)
  })
_sym_db.RegisterMessage(ExpertSuitableResponse)

SuitabilityPrediction = _reflection.GeneratedProtocolMessageType('SuitabilityPrediction', (_message.Message,), {
  'DESCRIPTOR' : _SUITABILITYPREDICTION,
  '__module__' : 'arg_services.quality.v1beta.expert_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.quality.v1beta.SuitabilityPrediction)
  })
_sym_db.RegisterMessage(SuitabilityPrediction)


DESCRIPTOR._options = None
_EXPERTSUITABLEREQUEST_FEATURESENTRY._options = None

_EXPERTSUITABILITYSERVICE = _descriptor.ServiceDescriptor(
  name='ExpertSuitabilityService',
  full_name='arg_services.quality.v1beta.ExpertSuitabilityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=936,
  serialized_end=1130,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExpertSuitable',
    full_name='arg_services.quality.v1beta.ExpertSuitabilityService.ExpertSuitable',
    index=0,
    containing_service=None,
    input_type=_EXPERTSUITABLEREQUEST,
    output_type=_EXPERTSUITABLERESPONSE,
    serialized_options=b'\202\323\344\223\002$:\001*\"\037/quality/v1beta/expert_suitable',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXPERTSUITABILITYSERVICE)

DESCRIPTOR.services_by_name['ExpertSuitabilityService'] = _EXPERTSUITABILITYSERVICE

# @@protoc_insertion_point(module_scope)
