# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.quality.v1beta import expert_pb2 as arg__services_dot_quality_dot_v1beta_dot_expert__pb2


class ExpertSuitabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExpertSuitable = channel.unary_unary(
                '/arg_services.quality.v1beta.ExpertSuitabilityService/ExpertSuitable',
                request_serializer=arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableRequest.SerializeToString,
                response_deserializer=arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableResponse.FromString,
                )


class ExpertSuitabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExpertSuitable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpertSuitabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExpertSuitable': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpertSuitable,
                    request_deserializer=arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableRequest.FromString,
                    response_serializer=arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.quality.v1beta.ExpertSuitabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExpertSuitabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExpertSuitable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.quality.v1beta.ExpertSuitabilityService/ExpertSuitable',
            arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableRequest.SerializeToString,
            arg__services_dot_quality_dot_v1beta_dot_expert__pb2.ExpertSuitableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
