# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.quality.v1beta import explanation_pb2 as arg__services_dot_quality_dot_v1beta_dot_explanation__pb2


class QualityExplanationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Explain = channel.unary_unary(
                '/arg_services.quality.v1beta.QualityExplanationService/Explain',
                request_serializer=arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainRequest.SerializeToString,
                response_deserializer=arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainResponse.FromString,
                )


class QualityExplanationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QualityExplanationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainRequest.FromString,
                    response_serializer=arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.quality.v1beta.QualityExplanationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QualityExplanationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.quality.v1beta.QualityExplanationService/Explain',
            arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainRequest.SerializeToString,
            arg__services_dot_quality_dot_v1beta_dot_explanation__pb2.ExplainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
