# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/ranking/v1beta/granularity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/ranking/v1beta/granularity.proto',
  package='arg_services.ranking.v1beta',
  syntax='proto3',
  serialized_options=b'\n\037com.arg_services.ranking.v1betaB\020GranularityProtoP\001\242\002\003ARX\252\002\032ArgServices.Ranking.V1beta\312\002\032ArgServices\\Ranking\\V1beta\342\002&ArgServices\\Ranking\\V1beta\\GPBMetadata\352\002\034ArgServices::Ranking::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-arg_services/ranking/v1beta/granularity.proto\x12\x1b\x61rg_services.ranking.v1beta\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"z\n\x1d\x46ineGranularClusteringRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n\x04\x61\x64us\x18\x02 \x03(\tR\x04\x61\x64us\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\xa7\x01\n\x1e\x46ineGranularClusteringResponse\x12T\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x32.arg_services.ranking.v1beta.GranularityPredictionR\x0bpredictions\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\x7f\n\x15GranularityPrediction\x12\x16\n\x06stance\x18\x01 \x01(\x01R\x06stance\x12\x14\n\x05\x66rame\x18\x02 \x01(\x01R\x05\x66rame\x12\x18\n\x07meaning\x18\x03 \x01(\x01R\x07meaning\x12\x1e\n\nhierarchic\x18\x04 \x01(\x01R\nhierarchic2\xdd\x01\n\x12GranularityService\x12\xc6\x01\n\x16\x46ineGranularClustering\x12:.arg_services.ranking.v1beta.FineGranularClusteringRequest\x1a;.arg_services.ranking.v1beta.FineGranularClusteringResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/ranking/v1beta/fine_granular_clusteringB\xbd\x01\n\x1f\x63om.arg_services.ranking.v1betaB\x10GranularityProtoP\x01\xa2\x02\x03\x41RX\xaa\x02\x1a\x41rgServices.Ranking.V1beta\xca\x02\x1a\x41rgServices\\Ranking\\V1beta\xe2\x02&ArgServices\\Ranking\\V1beta\\GPBMetadata\xea\x02\x1c\x41rgServices::Ranking::V1betab\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_FINEGRANULARCLUSTERINGREQUEST = _descriptor.Descriptor(
  name='FineGranularClusteringRequest',
  full_name='arg_services.ranking.v1beta.FineGranularClusteringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='arg_services.ranking.v1beta.FineGranularClusteringRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='query', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adus', full_name='arg_services.ranking.v1beta.FineGranularClusteringRequest.adus', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='adus', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.ranking.v1beta.FineGranularClusteringRequest.extras', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=260,
)


_FINEGRANULARCLUSTERINGRESPONSE = _descriptor.Descriptor(
  name='FineGranularClusteringResponse',
  full_name='arg_services.ranking.v1beta.FineGranularClusteringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predictions', full_name='arg_services.ranking.v1beta.FineGranularClusteringResponse.predictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='predictions', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.ranking.v1beta.FineGranularClusteringResponse.extras', index=1,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=430,
)


_GRANULARITYPREDICTION = _descriptor.Descriptor(
  name='GranularityPrediction',
  full_name='arg_services.ranking.v1beta.GranularityPrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stance', full_name='arg_services.ranking.v1beta.GranularityPrediction.stance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='stance', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='arg_services.ranking.v1beta.GranularityPrediction.frame', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='frame', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meaning', full_name='arg_services.ranking.v1beta.GranularityPrediction.meaning', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='meaning', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hierarchic', full_name='arg_services.ranking.v1beta.GranularityPrediction.hierarchic', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hierarchic', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=559,
)

_FINEGRANULARCLUSTERINGREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_FINEGRANULARCLUSTERINGRESPONSE.fields_by_name['predictions'].message_type = _GRANULARITYPREDICTION
_FINEGRANULARCLUSTERINGRESPONSE.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['FineGranularClusteringRequest'] = _FINEGRANULARCLUSTERINGREQUEST
DESCRIPTOR.message_types_by_name['FineGranularClusteringResponse'] = _FINEGRANULARCLUSTERINGRESPONSE
DESCRIPTOR.message_types_by_name['GranularityPrediction'] = _GRANULARITYPREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FineGranularClusteringRequest = _reflection.GeneratedProtocolMessageType('FineGranularClusteringRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINEGRANULARCLUSTERINGREQUEST,
  '__module__' : 'arg_services.ranking.v1beta.granularity_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.ranking.v1beta.FineGranularClusteringRequest)
  })
_sym_db.RegisterMessage(FineGranularClusteringRequest)

FineGranularClusteringResponse = _reflection.GeneratedProtocolMessageType('FineGranularClusteringResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINEGRANULARCLUSTERINGRESPONSE,
  '__module__' : 'arg_services.ranking.v1beta.granularity_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.ranking.v1beta.FineGranularClusteringResponse)
  })
_sym_db.RegisterMessage(FineGranularClusteringResponse)

GranularityPrediction = _reflection.GeneratedProtocolMessageType('GranularityPrediction', (_message.Message,), {
  'DESCRIPTOR' : _GRANULARITYPREDICTION,
  '__module__' : 'arg_services.ranking.v1beta.granularity_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.ranking.v1beta.GranularityPrediction)
  })
_sym_db.RegisterMessage(GranularityPrediction)


DESCRIPTOR._options = None

_GRANULARITYSERVICE = _descriptor.ServiceDescriptor(
  name='GranularityService',
  full_name='arg_services.ranking.v1beta.GranularityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=562,
  serialized_end=783,
  methods=[
  _descriptor.MethodDescriptor(
    name='FineGranularClustering',
    full_name='arg_services.ranking.v1beta.GranularityService.FineGranularClustering',
    index=0,
    containing_service=None,
    input_type=_FINEGRANULARCLUSTERINGREQUEST,
    output_type=_FINEGRANULARCLUSTERINGRESPONSE,
    serialized_options=b'\202\323\344\223\002-:\001*\"(/ranking/v1beta/fine_granular_clustering',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRANULARITYSERVICE)

DESCRIPTOR.services_by_name['GranularityService'] = _GRANULARITYSERVICE

# @@protoc_insertion_point(module_scope)
