# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.ranking.v1beta import granularity_pb2 as arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2


class GranularityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FineGranularClustering = channel.unary_unary(
                '/arg_services.ranking.v1beta.GranularityService/FineGranularClustering',
                request_serializer=arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringRequest.SerializeToString,
                response_deserializer=arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringResponse.FromString,
                )


class GranularityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FineGranularClustering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GranularityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FineGranularClustering': grpc.unary_unary_rpc_method_handler(
                    servicer.FineGranularClustering,
                    request_deserializer=arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringRequest.FromString,
                    response_serializer=arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.ranking.v1beta.GranularityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GranularityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FineGranularClustering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.ranking.v1beta.GranularityService/FineGranularClustering',
            arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringRequest.SerializeToString,
            arg__services_dot_ranking_dot_v1beta_dot_granularity__pb2.FineGranularClusteringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
