# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.ranking.v1beta import ranking_pb2 as arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2


class RankingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QualityRanking = channel.unary_unary(
                '/arg_services.ranking.v1beta.RankingService/QualityRanking',
                request_serializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingRequest.SerializeToString,
                response_deserializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingResponse.FromString,
                )
        self.StatisticalRanking = channel.unary_unary(
                '/arg_services.ranking.v1beta.RankingService/StatisticalRanking',
                request_serializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingRequest.SerializeToString,
                response_deserializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingResponse.FromString,
                )


class RankingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QualityRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatisticalRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QualityRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.QualityRanking,
                    request_deserializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingRequest.FromString,
                    response_serializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingResponse.SerializeToString,
            ),
            'StatisticalRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.StatisticalRanking,
                    request_deserializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingRequest.FromString,
                    response_serializer=arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.ranking.v1beta.RankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RankingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QualityRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.ranking.v1beta.RankingService/QualityRanking',
            arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingRequest.SerializeToString,
            arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.QualityRankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StatisticalRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.ranking.v1beta.RankingService/StatisticalRanking',
            arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingRequest.SerializeToString,
            arg__services_dot_ranking_dot_v1beta_dot_ranking__pb2.StatisticalRankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
