# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining_explanation/v1beta/adu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arg_services/mining_explanation/v1beta/adu.proto',
  package='arg_services.mining_explanation.v1beta',
  syntax='proto3',
  serialized_options=b'\n*com.arg_services.mining_explanation.v1betaB\010AduProtoP\001\242\002\003AMX\252\002$ArgServices.MiningExplanation.V1beta\312\002$ArgServices\\MiningExplanation\\V1beta\342\0020ArgServices\\MiningExplanation\\V1beta\\GPBMetadata\352\002&ArgServices::MiningExplanation::V1beta',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0arg_services/mining_explanation/v1beta/adu.proto\x12&arg_services.mining_explanation.v1beta\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x80\x01\n\x15\x43lassificationRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language\x12\x1a\n\x08segments\x18\x02 \x03(\tR\x08segments\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"\x96\x01\n\x16\x43lassificationResponse\x12K\n\x08segments\x18\x01 \x03(\x0b\x32/.arg_services.mining_explanation.v1beta.SegmentR\x08segments\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"L\n\x07Segment\x12\'\n\x0fkeyword_markers\x18\x01 \x03(\x08R\x0ekeywordMarkers\x12\x18\n\x07\x63lauses\x18\x02 \x03(\tR\x07\x63lauses2\xe3\x01\n\x15\x41\x64uExplanationService\x12\xc9\x01\n\x0e\x43lassification\x12=.arg_services.mining_explanation.v1beta.ClassificationRequest\x1a>.arg_services.mining_explanation.v1beta.ClassificationResponse\"8\x82\xd3\xe4\x93\x02\x32:\x01*\"-/mining_explanation/v1beta/adu/classificationB\xe8\x01\n*com.arg_services.mining_explanation.v1betaB\x08\x41\x64uProtoP\x01\xa2\x02\x03\x41MX\xaa\x02$ArgServices.MiningExplanation.V1beta\xca\x02$ArgServices\\MiningExplanation\\V1beta\xe2\x02\x30\x41rgServices\\MiningExplanation\\V1beta\\GPBMetadata\xea\x02&ArgServices::MiningExplanation::V1betab\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CLASSIFICATIONREQUEST = _descriptor.Descriptor(
  name='ClassificationRequest',
  full_name='arg_services.mining_explanation.v1beta.ClassificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='arg_services.mining_explanation.v1beta.ClassificationRequest.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='language', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segments', full_name='arg_services.mining_explanation.v1beta.ClassificationRequest.segments', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='segments', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining_explanation.v1beta.ClassificationRequest.extras', index=2,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=281,
)


_CLASSIFICATIONRESPONSE = _descriptor.Descriptor(
  name='ClassificationResponse',
  full_name='arg_services.mining_explanation.v1beta.ClassificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='arg_services.mining_explanation.v1beta.ClassificationResponse.segments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='segments', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extras', full_name='arg_services.mining_explanation.v1beta.ClassificationResponse.extras', index=1,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='extras', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=434,
)


_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='arg_services.mining_explanation.v1beta.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword_markers', full_name='arg_services.mining_explanation.v1beta.Segment.keyword_markers', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='keywordMarkers', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clauses', full_name='arg_services.mining_explanation.v1beta.Segment.clauses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='clauses', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=512,
)

_CLASSIFICATIONREQUEST.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_CLASSIFICATIONRESPONSE.fields_by_name['segments'].message_type = _SEGMENT
_CLASSIFICATIONRESPONSE.fields_by_name['extras'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['ClassificationRequest'] = _CLASSIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['ClassificationResponse'] = _CLASSIFICATIONRESPONSE
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassificationRequest = _reflection.GeneratedProtocolMessageType('ClassificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONREQUEST,
  '__module__' : 'arg_services.mining_explanation.v1beta.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining_explanation.v1beta.ClassificationRequest)
  })
_sym_db.RegisterMessage(ClassificationRequest)

ClassificationResponse = _reflection.GeneratedProtocolMessageType('ClassificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONRESPONSE,
  '__module__' : 'arg_services.mining_explanation.v1beta.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining_explanation.v1beta.ClassificationResponse)
  })
_sym_db.RegisterMessage(ClassificationResponse)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'arg_services.mining_explanation.v1beta.adu_pb2'
  # @@protoc_insertion_point(class_scope:arg_services.mining_explanation.v1beta.Segment)
  })
_sym_db.RegisterMessage(Segment)


DESCRIPTOR._options = None

_ADUEXPLANATIONSERVICE = _descriptor.ServiceDescriptor(
  name='AduExplanationService',
  full_name='arg_services.mining_explanation.v1beta.AduExplanationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=515,
  serialized_end=742,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classification',
    full_name='arg_services.mining_explanation.v1beta.AduExplanationService.Classification',
    index=0,
    containing_service=None,
    input_type=_CLASSIFICATIONREQUEST,
    output_type=_CLASSIFICATIONRESPONSE,
    serialized_options=b'\202\323\344\223\0022:\001*\"-/mining_explanation/v1beta/adu/classification',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADUEXPLANATIONSERVICE)

DESCRIPTOR.services_by_name['AduExplanationService'] = _ADUEXPLANATIONSERVICE

# @@protoc_insertion_point(module_scope)
