# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arg_services.mining_explanation.v1beta import major_claim_pb2 as arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2


class MajorClaimExplanationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MajorClaim = channel.unary_unary(
                '/arg_services.mining_explanation.v1beta.MajorClaimExplanationService/MajorClaim',
                request_serializer=arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimRequest.SerializeToString,
                response_deserializer=arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimResponse.FromString,
                )


class MajorClaimExplanationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MajorClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MajorClaimExplanationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MajorClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.MajorClaim,
                    request_deserializer=arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimRequest.FromString,
                    response_serializer=arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arg_services.mining_explanation.v1beta.MajorClaimExplanationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MajorClaimExplanationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MajorClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arg_services.mining_explanation.v1beta.MajorClaimExplanationService/MajorClaim',
            arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimRequest.SerializeToString,
            arg__services_dot_mining__explanation_dot_v1beta_dot_major__claim__pb2.MajorClaimResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
